---
- hosts: localhost
  roles:
    - common
    - nats
    - role: geerlingguy.nodejs
      nodejs_version: "12.x"
      become: yes
    - backend_service
    - frontend_service
    - rtc
    - role: infothrill.rpi-boot-config
      boot_config_lines: ['dtoverlay=i2c-rtc,pcf8523']
      become: yes
